import re
p = re.compile('ab?c')
m = p.match('ac')
print(m)
p = re.compile('ab?c')
m = p.match('abc')
print(m)
p = re.compile('ab?c')
m = p.match('abbc')
print(m)
p = re.compile('ab?c')
m = p.match('abbbc')
print(m)
p = re.compile('ab?c')
m = p.match('abcd')
print(m)